### PR TITLE
Config error handling

### PR DESCRIPTION
**Pull request by kthare10**
Addresses following issues:
#300 
#299

### CODE REVIEW

**Review by paul-ruth — APPROVED** [review]

**Review by sajith — APPROVED** [review]
Some minor comments, but hopefully should be okay even without addressing them.

I was also wondering if `validate_config()` (or the new equivalent) should be done in two steps: `generate_ssh_keys()` and then `verify_config()`.  This way:

- The steps would be explicit rather than implicit (no surprises when a validate method attempts to write files); and 
- If someone has ssh keys they've generated themselves, they can still benefit from `verify_config()`.

**Comment by sajith** [comment]
Oops, this got merged when I wandered away for a few minutes. :-)

**Comment by sajith** [comment]
@kthare10 I will file some issues and start a PR if my suggestions make sense. What do you think?

**Comment by kthare10** [comment]
Agree on attempting to create directory before failing.
Regarding separate verify_config and generate_ssh_keys call. 
- instead have two verify and configure 
- Verify just validates like you suggested
- configure does all things involving generation of files (keys/ssh_config) or any additional things

**Pull request merged**
