### PR TITLE
Adding pretty names for FPGA columns

### PR DESCRIPTION
**Pull request by ibaldin**
very simple fix

I need this to be usable in 'beyond bleeding edge' container.

### CODE REVIEW

**Review by kthare10 — APPROVED** [review]
Looks good!

**Review by sajith — APPROVED** [review]
Re-ran black so that that check passes.

**Comment by ibaldin** [comment]
can we merge this - i need it to be in the 'beyond bleeding edge' container

**Comment by sajith** [comment]
> can we merge this - i need it to be in the 'beyond bleeding edge' container

Done! Sorry, this got buried in my GitHub alerts.

**Pull request merged**
