### PR TITLE
Clean up bastion connections

### PR DESCRIPTION
**Pull request by sajith**
Issue is #110.

### CODE REVIEW

**Comment by sajith** [comment]
> Please update `requirements.txt` to include `fabrictestbed==1.3.3`. [For Python3.10 installs] Also please bump the version number in `fabrictestbed_extensions/__init__.py` to `1.3.4`.

@kthare10, would you like me to make both those things in this PR, or do we need a separate PR?

I guess a separate PR would be either "the right thing to do" or "just more busywork", depending on who you ask.  I'll accept your preference. :-)

**Comment by kthare10** [comment]
> > Please update `requirements.txt` to include `fabrictestbed==1.3.3`. [For Python3.10 installs] Also please bump the version number in `fabrictestbed_extensions/__init__.py` to `1.3.4`.
> 
> @kthare10, would you like me to make both those things in this PR, or do we need a separate PR?
> 
> I guess a separate PR would be either "the right thing to do" or "just more busywork", depending on who you ask. I'll accept your preference. :-)

@sajith - I don't have a preference :) I am okay with what works best for you.

**Comment by sajith** [comment]
@kthare10 Well, I made those changes on this PR just so that there aren't two PRs to be reviewed and approved today.  Not sure if this really is my preference but this seems quicker since we're trying to get a release out.

Since both @paul-ruth and I have made commits to this PR branch, could you give this PR a review/approval? Thanks!

**Review by kthare10 — APPROVED** [review]
Looks good

**Pull request merged**
