### PR TITLE
fixed l2bridge nstype check

### PR DESCRIPTION
**Pull request by paul-ruth**
Fix for nstype check fix from yesterday.

### CODE REVIEW

**Review by sajith — APPROVED** [review]

**Comment by sajith** [comment]
The changelog check is failing because I misunderstood how PR labels work: the "no changelog" label should be added at the time of PR creation, not later. 

Filed https://github.com/fabric-testbed/fabrictestbed-extensions/issues/149

**Comment by paul-ruth** [comment]
Do I need do something to get this merged?  Also, you can create another rc<n+1> in pypi

**Comment by sajith** [comment]
> Do I need do something to get this merged? Also, you can create another rc<n+1> in pypi

I will bump up the version in this branch and post 1.4.2rc4 to PyPI.

**Comment by sajith** [comment]
Actions: 

- Merged `main` onto this branch to update things.
- Bumped up version to rel1.4.2-rc4, built package, published on PyPI ([ref](https://pypi.org/project/fabrictestbed-extensions/1.4.2rc4/)).
- Resolved merge conflict (against `main`) after bumping up version.
- Will merge this PR to `main` now.

**Pull request merged**
