### PR TITLE
Add a publish workflow

### LINKED ISSUE #224: Release automation
Let us add (yet another!) GitHub Actions workflow such that:

- Pushing a matching release tag would run tests, build the package, and publish the packages built on CI on PyPI.
- This should also "activate" the corresponding version on readthedocs project. Currently this is a manual process, and I often forget to do this step.

PyPI now has the concept of [trusted publishers](https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/) and there's a GitHub [Action](https://github.com/marketplace/actions/pypi-publish) for publishing packages on PyPI, both of which are useful.

Upside is that some more steps would be automated, which will eliminate some mistakes like forgetting to activate an API doc version on ReadTheDocs or forgetting to push a release tag to GitHub.  Downside is that fablib has already become a special snowflake in the FABRIC universe with all these annoying CI bureaucracy. ;-)

### PR DESCRIPTION
**Pull request by sajith**
Resolves #224.  Changes:

- Add a "publish" workflow, which will be triggered when a tag matching the regexp `rel*` is pushed to this repository.  The workflow will run the unit tests, build sdist and wheel packages, and publish them to PyPI.
- There are no long-lived tokens or user/password combos involved, because, on PyPI, this GitHub repo is configured as a [trusted publisher](https://docs.pypi.org/trusted-publishers/). A short-lived token will be used instead.

[Here](https://github.com/fabric-testbed/fabrictestbed-extensions/actions/runs/6163978928) is an example workflow run.

### CODE REVIEW

**Review by kthare10 — APPROVED** [review]
Looks good!

Also, would this workflow create a github release too?

**Comment by sajith** [comment]
> Also, would this workflow create a github release too?

Not yet, but it is a good idea.  Thank you!  I guess I asked for a review too early. :-)

Let me look into that.

**Review by kthare10 — APPROVED** [review]
+1

**Comment by sajith** [comment]
@kthare10 Now this workflow can create GitHub releases too! We basically run [GitHub CLI](https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows) with  `gh release create <tag> --title "Release X.Y.Z" --generate-notes`.

https://github.com/fabric-testbed/fabrictestbed-extensions/releases/tag/rel1.5.6rc7 is an example release created by the workflow.  I will remove it once this PR gets merged.

image

**Pull request merged**
