### PR TITLE
Al2s support

### PR DESCRIPTION
**Pull request by kthare10**
Changes to support AL2S provisioning used by Fabfed
#325

### CODE REVIEW

**Comment by kthare10** [comment]
@sajith - Not sure what's the issue with black. I don't see any errors when I run it in my local env both with python3.9 and python3.11

**Comment by sajith** [comment]
@kthare10 Do you have black 24 in your local environment?  We upgraded from black 23 in https://github.com/fabric-testbed/fabrictestbed-extensions/pull/311...

You can run `tox -e format` so that the correct versions of black and isort will run.

**Comment by kthare10** [comment]
@sajith I seem to have the correct version.

```
(cli) RENCI_C02G902WML86:fabrictestbed-extensions kthare10$ tox -e format
format: install_deps> python -I -m pip install 'black==24.*' 'isort==5.*'
format: commands[0]> black fabrictestbed_extensions tests
All done! ✨ 🍰 ✨
39 files left unchanged.
format: commands[1]> isort fabrictestbed_extensions tests
  format: OK (7.41=setup[3.27]+cmd[3.68,0.46] seconds)
  congratulations :) (7.49 seconds)
(cli) RENCI_C02G902WML86:fabrictestbed-extensions kthare10$
(cli) RENCI_C02G902WML86:fabrictestbed-extensions kthare10$ git status
On branch al2s-support
Your branch is up to date with 'origin/al2s-support'.

nothing to commit, working tree clean
(cli) RENCI_C02G902WML86:fabrictestbed-extensions kthare10$
(cli) RENCI_C02G902WML86:fabrictestbed-extensions kthare10$
(cli) RENCI_C02G902WML86:fabrictestbed-extensions kthare10$ python --version
Python 3.11.6
(cli) RENCI_C02G902WML86:fabrictestbed-extensions kthare10$
(cli) RENCI_C02G902WML86:fabrictestbed-extensions kthare10$ pip list | grep black
black                      24.4.2
```

**Comment by sajith** [comment]
@kthare10 Huh, that is annoying. Let me look into that.

**Comment by sajith** [comment]
@kthare10  Oh now I know what is going on. :-)

The `pull_request_target` trigger causes the base of the branch (e9ceeac873975c8a1047ef22c38c251d5977c466) to be checked out, not the HEAD of the branch, and there is code in the base that black do not like.  I think only the signed commits check recommends using `pull_request_target` as the trigger.

I will do some clean up in a separate PR.  For the purpose of this PR, we can treat black's output like noise.

**Pull request merged**
