### PR TITLE
fixed registry mirror for ubuntu 22

### PR DESCRIPTION
**Pull request by silvertenor**
Changed registry to include https:// in front. Wasn't working for ubuntu 22 but now it is.

### CODE REVIEW

**Comment by silvertenor** [comment]
@sajith I believe the `black` my machine was using was the one installed by homebrew. I changed this to point to the correct version of black and reformatted; it looks like everything worked this way.

Thank you!

**Comment by sajith** [comment]
@silvertenor Thanks! I was still confused by the size of the diff, and then I realized that you want to merge your PR branch to to [124.add_remove_ifaces_from_network](https://github.com/fabric-testbed/fabrictestbed-extensions/tree/124.add_remove_ifaces_from_network) branch (which is @paul-ruth's work-in-progress branch, I believe), and not `main`.  Is that really so?  And if it is so, why is that?

If you want to merge this PR against Paul's branch, Paul is the right reviewer. :-)

**Comment by silvertenor** [comment]
@sajith That is correct, I am working with @paul-ruth on his branch. If I tried merging into main it would probably break the current version of fablib. We are working on the next release. Hopefully this makes sense

**Comment by silvertenor** [comment]
@paul-ruth I checked the conflicts and accepted your incoming changes from the latest update. This should now allow docker to work for all three images.

**Pull request merged**
